export default function Head() {
  return (
    <>
      <title>Product List App</title>
      <meta content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create-next-app" />
      <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    </>
  );
}
