'use client';

import { Toaster } from 'react-hot-toast';

import NavBar from '@/components/Navbar';

import { Providers } from '@/redux/provider';

import GlobalStyle from '../GlobalStyles';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Product List App</title>
        <meta content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body>
        <GlobalStyle />
        <Toaster />
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
