'use client';

import { Toaster } from 'react-hot-toast';

import NavBar from '@/components/Navbar';

import { Providers } from '@/redux/provider';

import GlobalStyle from '../GlobalStyles';

export const metadata = {
  title: 'Product List App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        <Toaster />
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
