'use client';

import Head from 'next/head';

import { Toaster } from 'react-hot-toast';

import NavBar from '@/components/Navbar';

import { Providers } from '@/redux/provider';

import GlobalStyle from '../GlobalStyles';

export const metadata = {
  title: 'Product List Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head /> */}
      <body>
        <GlobalStyle />
        <Toaster />
        <Providers>
          <NavBar />
          <Head>
        <title>Product List App</title>
        <meta content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
          {children}
        </Providers>
      </body>
    </html>
  );
}
